# Generated by Django 2.0.3 on 2018-03-20 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Rule name', unique=True)),
                ('type', models.CharField(choices=[('r', 'regex')], default='regex', help_text='Rule type', max_length=1)),
                ('value', models.TextField(help_text='Rule searching attribute (regex, string, xpath)')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='rule',
            unique_together={('name', 'created_by')},
        ),
    ]
