# Generated by Django 2.0.3 on 2018-03-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='type',
            field=models.CharField(choices=[('r', 'regex')], default='regex', max_length=1),
        ),
    ]
