# Generated by Django 2.0.3 on 2018-03-22 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rule', '0002_auto_20180321_1252'),
        ('django_apscheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('scraped_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('interval', models.IntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_apscheduler.DjangoJob')),
                ('rules', models.ManyToManyField(to='rule.Rule')),
            ],
        ),
        migrations.CreateModel(
            name='WebArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.FilePathField()),
                ('archive_hash', models.TextField()),
                ('accessed_time', models.DateTimeField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Task')),
            ],
        ),
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='webarchive',
            name='web_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.WebPage'),
        ),
        migrations.AddField(
            model_name='task',
            name='web_pages',
            field=models.ManyToManyField(to='task.WebPage'),
        ),
        migrations.AddField(
            model_name='metainfo',
            name='web_archive_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.WebArchive'),
        ),
        migrations.AlterUniqueTogether(
            name='webpage',
            unique_together={('url', 'created_by')},
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('name', 'created_by')},
        ),
    ]
