# Generated by Django 2.1 on 2018-08-20 22:08

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_apscheduler', '0002_auto_20180412_0758'),
        ('rule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('interval', models.IntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_apscheduler.DjangoJob')),
                ('rules', models.ManyToManyField(to='rule.Rule')),
            ],
        ),
        migrations.CreateModel(
            name='WebArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.FilePathField()),
                ('archive_hash', models.TextField()),
                ('accessed_time', models.DateTimeField()),
                ('scraped_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Task')),
            ],
            options={
                'ordering': ['-accessed_time'],
            },
        ),
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='webarchive',
            name='web_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_page', to='task.WebPage'),
        ),
        migrations.AddField(
            model_name='task',
            name='web_pages',
            field=models.ManyToManyField(to='task.WebPage'),
        ),
        migrations.AlterUniqueTogether(
            name='webpage',
            unique_together={('url', 'created_by')},
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('name', 'created_by')},
        ),
    ]
