# Generated by Django 2.0.3 on 2018-03-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metainfo',
            name='web_archive_instance',
        ),
        migrations.AddField(
            model_name='webarchive',
            name='scraped_data',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MetaInfo',
        ),
    ]
