# Generated by Django 2.0.3 on 2018-03-27 08:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20180327_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webarchive',
            name='scraped_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
