# Generated by Django 2.0.3 on 2018-03-27 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20180327_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webarchive',
            name='web_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_page', to='task.WebPage'),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
