# Generated by Django 2.0.3 on 2018-04-03 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20180327_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_apscheduler.DjangoJob'),
        ),
    ]
