# Generated by Django 2.0.3 on 2018-04-04 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20180403_2240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webarchive',
            options={'ordering': ['-accessed_time']},
        ),
    ]
